### ISSUE TITLE
Compile without NSM

### ISSUE THREAD

**Issue by trebmuh** [kmatheussen/radium_compressor#1]
Hi, is there a compilation option to build radium_compressor without the NSM support ? I don't have it installed on my computer and can't built it then.
Cheers

**Comment by kmatheussen** [comment]
Hi, quick reply, haven't had time to reply your private email yet. Just revert the last commit:
git revert 1614a363a380e1b12ff056ac74f49003cedfe475

**Comment by trebmuh** [comment]
Thanks for your quick answer. It works as expected.
Closing this Issue then.
Thank you.

**Comment by mxmilkiib** [comment]
I'm trying to build but currently getting
```
...
g++ -DDEBUG  -Wall -msse -mfpmath=sse -DUSE_QT_REQTYPE -DUSE_QT4 -g -I. -IQt -fPIC -Wno-class-memaccess main.cpp Qt_SliderPainter.o system_compressor_wrapper.o myladspa.o -DCOMPILING_STANDALONE -Iaudio/faudiostream/architecture/ `pkg-config --cflags Qt5Widgets --libs Qt5Core --libs Qt5Widgets` `pkg-config --cflags --libs liblo`  -ljack -o radium_compressor  -O3 -ffast-math
main.cpp:25:10: fatal error: nonlib/nsm.h: No such file or directory
   25 | #include "nonlib/nsm.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
```
I'm not sure how to resolve currently as pkgfile says the Arch non-session-manager package doesn't have nsm.h. It says hydrogen does, but installing that doesn't work. (Not that it matters but I use [RaySession](https://github.com/Houston4444/RaySession) for session management these days, which is NSM API compatible.)

**Comment by kmatheussen** [comment]
This should work:
1. Download nonlib/nsm.h from somewhere.
2. mkdir nonlib
3. cp nsm.h nonlib/

**Comment by kmatheussen** [comment]
I've attached an nsm.h file I found somewhere on github. The above recipe works for me. I don't have an nsm-devel package on my system either.
[nsm.h.gz](https://github.com/kmatheussen/radium_compressor/files/3568680/nsm.h.gz)

**Comment by kmatheussen** [comment]
From the documentation of nsm, you are actually supposed to include that file into your own repositories, so I've done that now.

**Comment by trebmuh** [comment]
:+1:
