### ISSUE TITLE
Issue when loading preset 

### ISSUE THREAD

**Issue by sub26nico** [kmatheussen/radium_compressor#4]
I'm not able to load presets, radium_compressor (Jack app) doesn't recall properly previous presets (made with the same version of radium_compressor). After loading preset, parameters values are not recalled and ratio and gain columns becomes blue. 

![radium](https://user-images.githubusercontent.com/23740642/64286960-c4f86780-cf5e-11e9-95d9-03740f9543a8.png)

LibraZiK distro (based on Debian 9) and radium_compressor 0.5.1.

**Comment by kmatheussen** [comment]
I don't know about the blue color, but for me it only seems like graphics is not updated. Is everything okay if you just resize the window a little bit after loading a preset?

**Comment by kmatheussen** [comment]
Can you try now?

**Comment by sub26nico** [comment]
> I don't know about the blue color, but for me it only seems like graphics is not updated. Is everything okay if you just resize the window a little bit after loading a preset?


No I already tried to resize and nothing more happens.
> Can you try now?

 I'll try the fix as soon as possible.

**Comment by sub26nico** [comment]
I tried with your fix but the issue is still there. I made a short video, hope that help. 
[]https://exode.me/videos/watch/8cbab057-6ce6-4b2a-80f6-501c60161369

Here the log : 
`sub26nico@debian:~$ radium_compressor


CREATING 1

the sample rate is now 44100/sec
Adding effect Ratio 0x5650f696e86c
Adding effect Threshold 0x5650f696e864
Adding effect Attack 0x5650f696e84c
Adding effect Release 0x5650f696e838
Adding effect Output Gain 0x5650f696e884
Adding effect bypass 0x5650f696e82c
Minimum height: 19, family: Sans Bold, font pixelsize: -1, font pointsize: 10
save pressed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Got it (nil) 0. Checked: 1
bypass: 1
Got it (nil) 0. Checked: 0
bypass: 0
Closing
sub26nico@debian:~$ radium_compressor


CREATING 1

the sample rate is now 44100/sec
Adding effect Ratio 0x55a471c75c6c
Adding effect Threshold 0x55a471c75c64
Adding effect Attack 0x55a471c75c4c
Adding effect Release 0x55a471c75c38
Adding effect Output Gain 0x55a471c75c84
Adding effect bypass 0x55a471c75c2c
Minimum height: 19, family: Sans Bold, font pixelsize: -1, font pointsize: 10
load pressed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
`

And the 'test4.rcc' file : 
`
2,038462
-20,571426
49,807373
100,236809
0,000000
3,200001
862
67
385
412
`

**Comment by kmatheussen** [comment]
Hi, seems like you have hit one of these insane "," vs. "." bugs. (the
".rcc" files contains "," instead of "." for decimals). This happens when
you don't use english locale.
I'll add a workaround.

**Comment by sub26nico** [comment]
I've edited the .rcc file with "." intead of "," and it's working.

**Comment by kmatheussen** [comment]
Should work now.

**Comment by sub26nico** [comment]
Yes, it works fine now, thanks for the quick fixes.
